### ISSUE TITLE
Bot duplication

### ISSUE THREAD

**Issue by kittenswolf** [brrm/ultimatewikibot#4]
Hello, author of /u/WikiTextBot here. I'm not sure why you need to run a bot when mine is already well-established (700k+ karma), and well over a year old.

**Can you please respond to this instead of closing this issue without comment?**

**Comment by brrm** [comment]
Sorry, I hadn't noticed another wikibot already existed when I developed this one.
I'll make sure my bot checks if /u/WikiTextBot has already replied to the comment or post to avoid duplicate responses.
While I implement this, I will temporarily suspend my bot. 
Does this sound like an agreeable solution to you?

**Comment by kittenswolf** [comment]
Hi,
since /u/WikiTextBot responds to all wikipedia links, checking if the bot already responded seems unnessecary. 
There are subreddits that have banned my bot for a reason, and a second wikibot will probably face the same fate in a given subreddit.

**Comment by brrm** [comment]
Closed since bot has now been shut down
